sudo: required
dist: trusty
language:
 - c
os:
 - linux
compiler:
 - gcc
   # - clang
before_install:
 - wget http://lv2plug.in/spec/lv2-1.12.0.tar.bz2
 - wget http://download.drobilla.net/serd-0.22.0.tar.bz2
 - wget http://download.drobilla.net/sord-0.14.0.tar.bz2
 - wget http://download.drobilla.net/sratom-0.4.6.tar.bz2
 - wget http://download.drobilla.net/lilv-0.22.0.tar.bz2
 - wget https://github.com/nanomsg/nanomsg/releases/download/0.8-beta/nanomsg-0.8-beta.tar.gz
 - tar xjf lv2-1.12.0.tar.bz2 
 - tar xjf serd-0.22.0.tar.bz2
 - tar xjf sord-0.14.0.tar.bz2
 - tar xjf sratom-0.4.6.tar.bz2
 - tar xjf lilv-0.22.0.tar.bz2
 - tar xzf nanomsg-0.8-beta.tar.gz
 - if [ "$CC" = "clang" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm-upper; fi
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:andykimpe/cmake
 - sudo add-apt-repository -y ppa:enlightenment-git/ppa
 - sudo apt-get update -qq
install:
 - if [ "$CC" = "clang" ]; then sudo apt-get install -y clang-3.6 libstdc++-5-dev; fi
 - if [ "$CC" = "gcc" ]; then sudo apt-get install -y gcc-5 g++-5; fi
 - sudo apt-get install -y libefl-dev
 - pushd lv2-1.12.0 && ./waf configure --no-plugins --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd serd-0.22.0 && ./waf configure --no-utils --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd sord-0.14.0 && ./waf configure --no-utils --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd sratom-0.4.6 && ./waf configure --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd lilv-0.22.0 && ./waf configure --no-utils --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd nanomsg-0.8-beta && ./configure --prefix=/usr && make && sudo make install && popd
before_script:
 - if [ "$CC" = "clang" ]; then export CXX="clang++-3.6" CC="clang-3.6" CFLAGS="-ffreestanding"; fi
 - if [ "$CC" = "gcc" ]; then export CXX="g++-5" CC="gcc-5"; fi
 - mkdir build && pushd build && cmake .. && popd
script:
 - pushd build && make && sudo make install && popd
