sudo: required
dist: trusty
language:
 - c
os:
 - linux
compiler:
 - gcc
   # - clang
before_install:
 - wget http://lv2plug.in/spec/lv2-1.12.0.tar.bz2
 - wget http://download.drobilla.net/serd-0.22.0.tar.bz2
 - wget http://download.drobilla.net/sord-0.14.0.tar.bz2
 - wget http://download.drobilla.net/sratom-0.4.6.tar.bz2
 - wget http://download.drobilla.net/lilv-0.22.0.tar.bz2
 - wget https://github.com/nanomsg/nanomsg/releases/download/0.8-beta/nanomsg-0.8-beta.tar.gz
 - tar xjf lv2-1.12.0.tar.bz2 
 - tar xjf serd-0.22.0.tar.bz2
 - tar xjf sord-0.14.0.tar.bz2
 - tar xjf sratom-0.4.6.tar.bz2
 - tar xjf lilv-0.22.0.tar.bz2
 - tar xzf nanomsg-0.8-beta.tar.gz
 - sudo add-apt-repository -y ppa:enlightenment-git/ppa
 - sudo apt-get -q update
install:
 - sudo apt-get install -y libefl-dev
 - pushd lv2-1.12.0 && ./waf configure --no-plugins --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd serd-0.22.0 && ./waf configure --no-utils --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd sord-0.14.0 && ./waf configure --no-utils --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd sratom-0.4.6 && ./waf configure --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd lilv-0.22.0 && ./waf configure --no-utils --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd nanomsg-0.8-beta && ./configure --prefix=/usr && make && sudo make install && popd
before_script:
 - mkdir build && pushd build && cmake .. && popd
script:
 - pushd build && make && sudo make install && popd
